# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/pinpoint
team: pus
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8991
healthcheck:
  liveness:
    path: pinpoint/internal/isAlive
  readiness:
    path: pinpoint/internal/isReady
prometheus:
  enabled: true
  path: pinpoint/internal/metrics
resources:
  limits:
    cpu: 2
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi
alertProfiles:
 - basic