# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/pinpoint
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: pinpoint/internal/isAlive
    initialDelay: 10
  readiness:
    path: pinpoint/internal/isReady
    initialDelay: 10
prometheus:
  enabled: true
  path: pinpoint/internal/metrics
resources:
  limits:
    cpu: 1
team: oppfolging
