name: Test, build, push and deploy

on: [push]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pinpoint:${{ github.sha }}
  TZ: Europe/Amsterdam

jobs:
  build:
    name: CI/CD pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build docker image
        run: |
          docker build --tag ${IMAGE} .

      - name: Push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-q0-fss:
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true
    steps:
      - uses: actions/checkout@v1

      - name: Deploy application to Q0 fss
        uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/dev'
        env:
          CLUSTER: dev-fss
          RESOURCE: nais-fss.yaml
          VAR: version=${{ github.sha }},namespace=q0

  deploy-q0-sbs:
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true
    steps:
      - uses: actions/checkout@v1

      - name: Deploy application to Q0 sbs
        uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/dev'
        env:
          CLUSTER: dev-sbs
          RESOURCE: nais-sbs.yaml
          VAR: version=${{ github.sha }},namespace=q0

  deploy-q1-sbs:
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true
    steps:
      - uses: actions/checkout@v1

      - name: Deploy application to Q1 sbs
        uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/dev'
        env:
          CLUSTER: dev-sbs
          RESOURCE: nais-sbs.yaml
          VAR: version=${{ github.sha }},namespace=q1

  deploy-prod-fss:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true
    steps:
      - uses: actions/checkout@v1
      - name: Deploy application to prod fss
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-fss
          RESOURCE: nais-fss.yaml
          VAR: version=${{ github.sha }},namespace=default

  deploy-prod-sbs:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true
    steps:
      - uses: actions/checkout@v1
      - name: Deploy application to prod sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-sbs
          RESOURCE: nais-sbs.yaml
          VAR: version=${{ github.sha }},namespace=default